name: terraform-apply

on:
  push:
    branches: [main]
    paths:
      - "envs/**"
      - "modules/**"
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to apply
        required: true
        type: choice
        options: [dev, prod]

permissions:
  contents: read

concurrency:
  group: terraform-apply-${{ inputs.environment || 'dev' }}
  cancel-in-progress: false

env:
  TF_VERSION: 1.15.8
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_ENV: ${{ inputs.environment || 'dev' }}
  TF_VAR_azs: ${{ vars.TF_AZS }}
  TF_VAR_kubernetes_version: ${{ vars.TF_KUBERNETES_VERSION }}
  TF_VAR_cluster_admin_arns: ${{ vars.TF_CLUSTER_ADMIN_ARNS }}
  TF_VAR_admin_cidrs: ${{ secrets.TF_ADMIN_CIDRS }}
  TF_VAR_alert_email: ${{ secrets.TF_ALERT_EMAIL }}

jobs:
  apply:
    name: apply-${{ inputs.environment || 'dev' }}
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment == 'prod' && 'production' || 'dev' }}
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: envs/${{ inputs.environment || 'dev' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          role-to-assume: ${{ vars.AWS_APPLY_ROLE_ARN }}
          aws-region: us-east-1

      - name: terraform init
        run: |
          terraform init -input=false \
            -backend-config="bucket=cloud-lab-platform-tfstate-510490942608" \
            -backend-config="key=envs/${TF_ENV}/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true" \
            -backend-config="use_lockfile=true"

      - name: terraform plan
        run: terraform plan -input=false -no-color -lock-timeout=60s -out=tfplan

      - name: terraform apply (exactly the plan above)
        run: terraform apply -input=false -no-color -lock-timeout=60s tfplan
